
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - run: npm ci
    - run: ./fern.js build configs/user-agent-ios.js
    - run: ./fern.js build configs/ghostery.js
    - run: ./fern.js build configs/ci/unit-tests.js
    - run: ./fern.js test configs/ci/unit-tests.js -l unit-node --environment testing --no-build --ci report.xml
