
name: Build configs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        config: ["configs/ghostery.js", "configs/user-agent-ios.js"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Upgrade npm
      run: npm install -g npm
    - run: npm ci
    - run: ./fern.js build ${{ matrix.config }}
